//! The controller: argv in, use cases out.
//!
//! This module and `main.rs` together are the **composition root** — the one
//! place allowed to know every layer at once, because choosing which adapter
//! satisfies which port is precisely its job. Note the shape of each handler:
//! construct the concrete adapters, call one use case, render the result. No
//! business logic reaches this far out.
//!
//! The operator defaults live here rather than in the layers they configure,
//! for the same reason: `data/feed.csv` is a deployment choice, not a fact
//! about feeds. The use cases receive a `FeedStore` that already knows where it
//! writes, and never see a path at all.

use crate::application::Result;
use crate::application::generate::generate_feed;
use crate::application::ports::{DatagramSink, FeedStore};
use crate::application::slice_one::{send_single, slice_one_message};
use crate::application::transmit::{DEFAULT_DEST, TransmitConfig, transmit_feed};
use crate::domain::codec::{ADD_ORDER_LEN, encode_add_order};
use crate::domain::market::MarketConfig;
use crate::domain::message::unpack_stock_symbol;
use crate::infrastructure::csv::CsvFeedStore;
use crate::infrastructure::net::udp::{UdpDatagramSink, UdpFeedTransmitter};
use crate::presentation::console::{ConsoleObserver, print_report};
use crate::presentation::format::{format_price, hex};
use crate::presentation::summary::summarise;

/// Where a generated feed lands when the operator names nothing else.
pub const DEFAULT_CSV: &str = "data/feed.csv";

pub const USAGE: &str = "\
usage: tx <command> [options]

  generate    generate a synthetic feed and write it to CSV
              --out PATH        (default data/feed.csv; also writes <stem>.symbols.csv)
              --count N         (default 100000)
              --seed N
              --interval-nanos N  simulated time between messages (default 100000)
              --quiet           skip the summary

  transmit     transmit a feed over UDP, one message per datagram
              --dest HOST:PORT  (default 192.168.252.18:9000)
              --rate HZ         messages/second, 0 for unpaced (default 10000)
              --csv PATH        send this file instead of generating
              --count N / --seed N   when generating

  summary   describe a feed without sending it
              --csv PATH        (default: generate one)
              --count N / --seed N

  one       slice 1: send a single hand-built Add Order
              [HOST[:PORT]]     (default 192.168.252.18:9000)

A CSV written by `gen` and a feed generated by `send` with the same --seed and
--count are the same messages, in the same order, byte for byte on the wire.";

/// Dispatches one command. Takes argv as a slice rather than reading the
/// environment so that a test can drive it.
pub fn run(args: &[String]) -> Result {
    let command = args.first().map(|s| s.as_str()).unwrap_or("help");

    match command {
        "generate" => generate(),
        "transmit" => transmit(),
        "summary" => summary(),
        "one" => transmit_one(),
        "help" | "-h" | "--help" => {
            println!("{USAGE}");
            Ok(())
        }
        other => Err(format!("unknown command {other:?}\n\n{USAGE}").into()),
    }
}

/// Generate a synthetic feed and write it to CSV.
fn generate() -> Result {
    // Default config is 100,000 messages at 10,000 messages/second (100 µs apart).
    let config = MarketConfig::default();
    let store = CsvFeedStore::new(DEFAULT_CSV);

    println!(
        "generating {} messages, seed {:#018x}, {} ns apart",
        config.count, config.seed, config.interval_nanos
    );

    let stored = generate_feed(&store, config)?;

    println!(
        "wrote {} rows to {} ({} bytes) and the locate map to {}",
        stored.rows, stored.feed_location, stored.feed_bytes, stored.symbols_location,
    );
    Ok(())
}

fn transmit() -> Result {
    let store = CsvFeedStore::new(DEFAULT_CSV);
    let mut transmitter = UdpFeedTransmitter::new();
    let mut observer = ConsoleObserver;
    let config = TransmitConfig::default();

    let report = transmit_feed(&store, &mut transmitter, &config, &mut observer)?;

    print_report(&report);
    Ok(())
}

fn summary() -> Result {
    let store = CsvFeedStore::new(DEFAULT_CSV);
    summarise(&store.load()?);
    Ok(())
}

/// Slice 1, unchanged: one hand-built Add Order as the entire payload.
fn transmit_one() -> Result {
    let dest = DEFAULT_DEST;
    let msg = slice_one_message()?;

    let mut buf = [0u8; ADD_ORDER_LEN];
    let n = encode_add_order(&msg, &mut buf)?;
    println!(
        "ItchAddOrder  {} {} {} shares @ {}",
        char::from(msg.buy_sell_indicator),
        unpack_stock_symbol(&{ msg.stock }),
        { msg.shares },
        format_price(msg.price),
    );
    println!("payload ({n} bytes):\n{}", hex(&buf[..n]));

    let sink = UdpDatagramSink::open(dest)?;
    let sent = send_single(&sink, &buf[..n])?;

    println!("sent {sent} bytes {} -> {dest}", sink.local_address()?);
    println!("(send_to succeeding means the kernel accepted the datagram, not that it arrived)");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    fn argv(s: &[&str]) -> Vec<String> {
        s.iter().map(|x| x.to_string()).collect()
    }

    #[test]
    fn help_is_the_default_and_an_unknown_command_is_an_error() {
        assert!(run(&argv(&[])).is_ok());
        assert!(run(&argv(&["help"])).is_ok());
        assert!(run(&argv(&["--help"])).is_ok());

        let err = run(&argv(&["nonsense"])).unwrap_err().to_string();
        assert!(err.contains("unknown command"), "{err}");
        assert!(err.contains("usage: tx"), "usage must follow the error");
    }

    /// The defaults the usage text promises are the defaults the code uses.
    #[test]
    fn documented_defaults_are_the_real_ones() {
        let market = MarketConfig::default();
        assert_eq!(market.count, 100_000);
        assert_eq!(
            market.interval_nanos, 100_000,
            "100 µs = 10,000 messages/second"
        );

        let transmit = TransmitConfig::default();
        assert_eq!(transmit.dest, "192.168.252.18:9000");
        assert_eq!(transmit.rate_hz, 10_000);
        assert_eq!(transmit.progress_every, Duration::from_secs(1));

        assert_eq!(DEFAULT_CSV, "data/feed.csv");
        for expected in [DEFAULT_CSV, "192.168.252.18:9000", "10000", "100000"] {
            assert!(
                USAGE.contains(expected),
                "usage does not mention {expected}"
            );
        }
    }
}
