//! Dependency-free (std only) ITCH 5.0 codec, market generator and UDP
//! transmitter.
//!
//! **Slice 1** (`docs/1_SLICE.md`): one Add Order message, alone, as the entire
//! UDP payload. No envelope, no sequence numbers, no framing. Still available as
//! the `one` subcommand.
//!
//! **Slice 2**: 1:1 message-to-datagram at a uniform 10,000 messages/second,
//! carrying a synthetic market whose behaviour modulates over the session, with
//! the whole stream written to CSV as ground truth for the receiver.
//!
//! What is deliberately still missing: sequence numbers, heartbeats, session
//! identity, end-of-session — everything that would let the receiver *quantify*
//! loss rather than merely suffer it. That is a session layer, it sits between
//! the ITCH messages and the datagram, and `docs/session-layer.md` designs it.

pub mod codec;
pub mod feed;
pub mod formatter;
pub mod market;
pub mod model;
pub mod pacer;
pub mod rng;
pub mod summary;
pub mod transmit;

use std::env;
use std::fs::{self, File};
use std::io::{self, BufReader, BufWriter, Write};
use std::net::{SocketAddr, ToSocketAddrs, UdpSocket};
use std::path::{Path, PathBuf};
use std::time::Duration;

use codec::{ADD_ORDER_LEN, encode_add_order};
use feed::{read_feed, write_feed, write_symbol_table};
use formatter::{format_price, hex};
use market::{DEFAULT_INTERVAL_NANOS, DEFAULT_MESSAGE_COUNT, MarketConfig, MarketSimulator};
use model::{
    ItchAddOrder, ItchMessage, pack_itch_timestamp, pack_stock_symbol, unpack_stock_symbol,
};
use transmit::{EncodedFeed, TransmitConfig, print_report, transmit};

pub const DEFAULT_DEST: &str = "192.168.252.18:9000";
pub const DEFAULT_PORT: &str = "9000";
pub const DEFAULT_CSV: &str = "data/feed.csv";
pub const DEFAULT_RATE_HZ: u64 = 10_000;

type Fallible = Result<(), Box<dyn std::error::Error>>;

const USAGE: &str = "\
usage: tx <command> [options]

  gen       generate a synthetic feed and write it to CSV
              --out PATH        (default data/feed.csv; also writes <stem>.symbols.csv)
              --count N         (default 100000)
              --seed N
              --interval-nanos N  simulated time between messages (default 100000)
              --quiet           skip the summary

  send      transmit a feed over UDP, one message per datagram
              --dest HOST:PORT  (default 192.168.252.18:9000)
              --rate HZ         messages/second, 0 for unpaced (default 10000)
              --csv PATH        send this file instead of generating
              --count N / --seed N   when generating

  summary   describe a feed without sending it
              --csv PATH        (default: generate one)
              --count N / --seed N

  one       slice 1: send a single hand-built Add Order
              [HOST[:PORT]]     (default 192.168.252.18:9000)

A CSV written by `gen` and a feed generated by `send` with the same --seed and
--count are the same messages, in the same order, byte for byte on the wire.";

pub fn run() -> Fallible {
    let args: Vec<String> = env::args().skip(1).collect();
    let (command, rest) = match args.split_first() {
        None => {
            println!("{USAGE}");
            return Ok(());
        }
        Some((c, r)) => (c.as_str(), r),
    };

    match command {
        "gen" => cmd_gen(&Args::parse(rest)?),
        "send" => cmd_send(&Args::parse(rest)?),
        "summary" => cmd_summary(&Args::parse(rest)?),
        "one" => cmd_one(rest.first().map(String::as_str)),
        "help" | "-h" | "--help" => {
            println!("{USAGE}");
            Ok(())
        }
        // Slice 1 took a bare address as its only argument. Keep that working
        // rather than failing on a command line that used to be correct.
        other if other.contains('.') || other.contains(':') => cmd_one(Some(other)),
        other => Err(format!("unknown command {other:?}\n\n{USAGE}").into()),
    }
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

fn cmd_gen(args: &Args) -> Fallible {
    let out = PathBuf::from(args.get("out").unwrap_or(DEFAULT_CSV));
    let config = args.market_config()?;

    if let Some(parent) = out.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)?;
        }
    }

    println!(
        "generating {} messages, seed {:#018x}, {} ns apart",
        config.count, config.seed, config.interval_nanos
    );

    let messages: Vec<ItchMessage> = MarketSimulator::new(config).collect();

    let mut file = BufWriter::new(File::create(&out)?);
    let rows = write_feed(&mut file, messages.iter().copied())?;
    file.flush()?;

    let symbols_path = symbols_path(&out);
    let mut symbols = BufWriter::new(File::create(&symbols_path)?);
    write_symbol_table(&mut symbols)?;
    symbols.flush()?;

    println!(
        "wrote {rows} rows to {} ({} bytes) and the locate map to {}",
        out.display(),
        fs::metadata(&out)?.len(),
        symbols_path.display(),
    );

    if !args.has("quiet") {
        println!();
        summary::summarise(&messages);
    }
    Ok(())
}

fn cmd_send(args: &Args) -> Fallible {
    let messages = args.load_messages()?;
    let rate_hz = args.parse_or("rate", DEFAULT_RATE_HZ)?;

    let encoded = EncodedFeed::encode_all(&messages)?;
    println!(
        "encoded {} messages into {} payload bytes ({:.1} bytes/datagram average)",
        encoded.len(),
        encoded.total_bytes(),
        encoded.total_bytes() as f64 / encoded.len().max(1) as f64,
    );

    let cfg = TransmitConfig {
        dest: args.get("dest").unwrap_or(DEFAULT_DEST).to_string(),
        rate_hz,
        progress_every: Duration::from_secs(1),
    };
    let report = transmit(&encoded, &cfg)?;
    print_report(&report);
    Ok(())
}

fn cmd_summary(args: &Args) -> Fallible {
    let messages = args.load_messages()?;
    summary::summarise(&messages);
    Ok(())
}

/// Slice 1, unchanged: one hand-built Add Order as the entire payload.
fn cmd_one(dest: Option<&str>) -> Fallible {
    let mut dest = dest.unwrap_or(DEFAULT_DEST).to_string();
    if !dest.contains(':') {
        dest.push(':');
        dest.push_str(DEFAULT_PORT);
    }

    let msg = ItchAddOrder {
        message_type: b'A',
        stock_locate: 7,
        tracking_number: 42,
        // 09:30:00.000000000 as nanoseconds since midnight.
        timestamp_bytes: pack_itch_timestamp(34_200_000_000_000)
            .ok_or("timestamp does not fit in 48 bits")?,
        order_reference: 1_234_567_890,
        buy_sell_indicator: b'B',
        shares: 100,
        stock: pack_stock_symbol("AAPL").ok_or("invalid stock symbol")?,
        price: 1_502_500, // $150.25, scaled by 10,000
    };

    let mut buf = [0u8; ADD_ORDER_LEN];
    let n = encode_add_order(&msg, &mut buf)?;

    println!(
        "ItchAddOrder  {} {} {} shares @ {}",
        char::from(msg.buy_sell_indicator),
        unpack_stock_symbol(&{ msg.stock }),
        { msg.shares },
        format_price(msg.price),
    );
    println!("payload ({n} bytes):\n{}", hex(&buf[..n]));

    // Bind to 0.0.0.0:0 — the kernel picks an ephemeral source port.
    let sock = UdpSocket::bind("0.0.0.0:0")?;
    let sent = sock.send_to(&buf[..n], dest.as_str())?;
    if sent != n {
        return Err(format!("short send: wrote {sent} of {n} bytes").into());
    }

    println!("sent {sent} bytes {} -> {dest}", sock.local_addr()?);
    println!("(send_to succeeding means the kernel accepted the datagram, not that it arrived)");
    Ok(())
}

// ---------------------------------------------------------------------------
// Plumbing
// ---------------------------------------------------------------------------

/// Resolves a destination, defaulting the port when only a host is given.
pub fn resolve(dest: &str) -> io::Result<SocketAddr> {
    let owned;
    let with_port = if dest.contains(':') {
        dest
    } else {
        owned = format!("{dest}:{DEFAULT_PORT}");
        &owned
    };
    with_port.to_socket_addrs()?.next().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::AddrNotAvailable,
            format!("{dest} resolved to no address"),
        )
    })
}

/// `data/feed.csv` -> `data/feed.symbols.csv`.
fn symbols_path(feed: &Path) -> PathBuf {
    let stem = feed
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_default();
    feed.with_file_name(format!("{stem}.symbols.csv"))
}

/// A very small `--key value` / `--key=value` parser.
///
/// Not a general argument library: it exists so the binary has no dependencies
/// and so an unrecognised flag is an error rather than a silent no-op.
struct Args {
    values: Vec<(String, Option<String>)>,
}

impl Args {
    fn parse(argv: &[String]) -> Result<Args, String> {
        let mut values = Vec::new();
        let mut i = 0;
        while i < argv.len() {
            let arg = &argv[i];
            let key = arg.strip_prefix("--").ok_or_else(|| {
                format!("expected an option starting with --, got {arg:?}\n\n{USAGE}")
            })?;
            match key.split_once('=') {
                Some((k, v)) => {
                    values.push((k.to_string(), Some(v.to_string())));
                    i += 1;
                }
                None => {
                    // A flag is bare if the next token is another option.
                    let next = argv.get(i + 1);
                    match next {
                        Some(v) if !v.starts_with("--") => {
                            values.push((key.to_string(), Some(v.clone())));
                            i += 2;
                        }
                        _ => {
                            values.push((key.to_string(), None));
                            i += 1;
                        }
                    }
                }
            }
        }
        Ok(Args { values })
    }

    fn get(&self, key: &str) -> Option<&str> {
        self.values
            .iter()
            .find(|(k, _)| k == key)
            .and_then(|(_, v)| v.as_deref())
    }

    fn has(&self, key: &str) -> bool {
        self.values.iter().any(|(k, _)| k == key)
    }

    fn parse_or<T: std::str::FromStr>(&self, key: &str, default: T) -> Result<T, String> {
        match self.get(key) {
            None => Ok(default),
            Some(v) => v
                .parse()
                .map_err(|_| format!("--{key} expects a number, got {v:?}")),
        }
    }

    fn market_config(&self) -> Result<MarketConfig, String> {
        let default = MarketConfig::default();
        Ok(MarketConfig {
            seed: self.parse_or("seed", default.seed)?,
            count: self.parse_or("count", DEFAULT_MESSAGE_COUNT)?,
            interval_nanos: self.parse_or("interval-nanos", DEFAULT_INTERVAL_NANOS)?,
        })
    }

    /// Either reads the feed from CSV or generates it. Generating is the
    /// default so the tool has no hidden dependency on a file existing; with
    /// the same seed and count the two are identical.
    fn load_messages(&self) -> Result<Vec<ItchMessage>, Box<dyn std::error::Error>> {
        match self.get("csv") {
            Some(path) => {
                let messages = read_feed(BufReader::new(File::open(path)?))?;
                println!("read {} messages from {path}", messages.len());
                Ok(messages)
            }
            None => {
                let config = self.market_config()?;
                println!(
                    "generating {} messages in memory, seed {:#018x} \
                     (identical to `gen --seed {} --count {}`)",
                    config.count, config.seed, config.seed, config.count
                );
                Ok(MarketSimulator::new(config).collect())
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn argv(s: &[&str]) -> Vec<String> {
        s.iter().map(|x| x.to_string()).collect()
    }

    #[test]
    fn args_accept_both_spellings() {
        let a = Args::parse(&argv(&["--count", "5", "--seed=7", "--quiet"])).unwrap();
        assert_eq!(a.get("count"), Some("5"));
        assert_eq!(a.get("seed"), Some("7"));
        assert!(a.has("quiet"));
        assert_eq!(a.get("quiet"), None);
        assert!(!a.has("nope"));
    }

    #[test]
    fn args_reject_a_stray_positional() {
        assert!(Args::parse(&argv(&["count", "5"])).is_err());
    }

    #[test]
    fn args_parse_numbers_and_report_bad_ones() {
        let a = Args::parse(&argv(&["--rate", "20000", "--count", "twelve"])).unwrap();
        assert_eq!(a.parse_or("rate", 1u64).unwrap(), 20_000);
        assert_eq!(a.parse_or("missing", 99u64).unwrap(), 99);
        assert!(a.parse_or("count", 1u64).is_err());
    }

    #[test]
    fn market_config_defaults_to_the_slice_2_numbers() {
        let cfg = Args::parse(&argv(&[])).unwrap().market_config().unwrap();
        assert_eq!(cfg.count, 100_000);
        assert_eq!(
            cfg.interval_nanos, 100_000,
            "100 µs = 10,000 messages/second"
        );
    }

    #[test]
    fn symbols_path_sits_beside_the_feed() {
        assert_eq!(
            symbols_path(Path::new("data/feed.csv")),
            Path::new("data/feed.symbols.csv")
        );
        assert_eq!(
            symbols_path(Path::new("run1.csv")),
            Path::new("run1.symbols.csv")
        );
    }

    #[test]
    fn resolve_supplies_the_default_port() {
        let a = resolve("127.0.0.1").unwrap();
        assert_eq!(a.port(), 9000);
        let b = resolve("127.0.0.1:1234").unwrap();
        assert_eq!(b.port(), 1234);
        assert!(resolve("not a host name at all").is_err());
    }

    /// The claim the usage text makes: the CSV and an in-memory generation with
    /// the same seed are the same feed.
    #[test]
    fn csv_and_in_memory_generation_agree() {
        let cfg = MarketConfig {
            count: 4_000,
            ..Default::default()
        };
        let generated: Vec<ItchMessage> = MarketSimulator::new(cfg).collect();
        let mut csv = Vec::new();
        write_feed(&mut csv, generated.iter().copied()).unwrap();
        assert_eq!(read_feed(csv.as_slice()).unwrap(), generated);
    }
}
