use realtime_stock_market_feed_transmitter::adapters::formatter::dramatic_display;
use realtime_stock_market_feed_transmitter::{
    Fallible, generate_signal, start_transmission, summarise, transmit_one,
};
use std::env;
use std::process;

fn main() {
    dramatic_display("RT Transmitter");
    if let Err(e) = run() {
        eprintln!("RT Transmitter encountered an error: {e}");
        process::exit(1);
    }
}
const USAGE: &str = "\
usage: tx <command> [options]

  generate    generate a synthetic feed and write it to CSV
              --out PATH        (default data/feed.csv; also writes <stem>.symbols.csv)
              --count N         (default 100000)
              --seed N
              --interval-nanos N  simulated time between messages (default 100000)
              --quiet           skip the summary

  transmit     transmit a feed over UDP, one message per datagram
              --dest HOST:PORT  (default 192.168.252.18:9000)
              --rate HZ         messages/second, 0 for unpaced (default 10000)
              --csv PATH        send this file instead of generating
              --count N / --seed N   when generating

  summary   describe a feed without sending it
              --csv PATH        (default: generate one)
              --count N / --seed N

  one       slice 1: send a single hand-built Add Order
              [HOST[:PORT]]     (default 192.168.252.18:9000)

A CSV written by `gen` and a feed generated by `send` with the same --seed and
--count are the same messages, in the same order, byte for byte on the wire.";

fn run() -> Fallible {
    let args: Vec<String> = env::args().skip(1).collect();
    let command = args.get(0).map(|s| s.as_str()).unwrap_or("help");

    match command {
        "generate" => generate_signal(),
        "transmit" => start_transmission(),
        "summary" => summarise(),
        "one" => transmit_one(),
        "help" | "-h" | "--help" => {
            println!("{USAGE}");
            Ok(())
        }
        other => Err(format!("unknown command {other:?}\n\n{USAGE}").into()),
    }
}
