use realtime_stock_market_feed_transmitter::formatter::dramatic_display;
use realtime_stock_market_feed_transmitter::{
    Args, Fallible, cmd_gen, cmd_one, cmd_send, cmd_summary,
};
use std::env;
use std::process;

fn main() {
    dramatic_display("RT Transmitter");
    if let Err(e) = run() {
        eprintln!("RT Transmitter encountered an error: {e}");
        process::exit(1);
    }
}

const USAGE: &str = "\
usage: tx <command> [options]

  gen       generate a synthetic feed and write it to CSV
              --out PATH        (default data/feed.csv; also writes <stem>.symbols.csv)
              --count N         (default 100000)
              --seed N
              --interval-nanos N  simulated time between messages (default 100000)
              --quiet           skip the summary

  send      transmit a feed over UDP, one message per datagram
              --dest HOST:PORT  (default 192.168.252.18:9000)
              --rate HZ         messages/second, 0 for unpaced (default 10000)
              --csv PATH        send this file instead of generating
              --count N / --seed N   when generating

  summary   describe a feed without sending it
              --csv PATH        (default: generate one)
              --count N / --seed N

  one       slice 1: send a single hand-built Add Order
              [HOST[:PORT]]     (default 192.168.252.18:9000)

A CSV written by `gen` and a feed generated by `send` with the same --seed and
--count are the same messages, in the same order, byte for byte on the wire.";

fn run() -> Fallible {
    let args: Vec<String> = env::args().skip(1).collect();
    let (command, rest) = match args.split_first() {
        None => {
            println!("{USAGE}");
            return Ok(());
        }
        Some((c, r)) => (c.as_str(), r),
    };

    println!("command: {command}");
    println!("rest: {rest:?}");

    match command {
        "gen" => {
            cmd_gen(&Args::parse(rest)?);
            Ok(())
        }
        "send" => {
            cmd_send(&Args::parse(rest)?);
            Ok(())
        }
        "summary" => {
            cmd_summary(&Args::parse(rest)?);
            Ok(())
        }
        "one" => {
            cmd_one(rest.first().map(String::as_str));
            Ok(())
        }
        "help" | "-h" | "--help" => {
            println!("{USAGE}");
            Ok(())
        }
        // Slice 1 took a bare address as its only argument. Keep that working
        // rather than failing on a command line that used to be correct.
        other if other.contains('.') || other.contains(':') => cmd_one(Some(other)),
        other => Err(format!("unknown command {other:?}\n\n{USAGE}").into()),
    }
}

